"""SolTrace 光线追踪适配器。

实现 OpticalModel 接口契约。当前阶段：可生成 SolTrace 输入脚本(.lk)，
但不在 macOS 本地执行光线追踪——efficiency/flux 接入实际 SolTrace 后启用。
接入方式见 https://github.com/NLR-SolTrace/SolTrace 的 coretrace 编译说明。
"""
from msptc.optics.base import OpticalModel, FluxProfile


class SolTraceAdapter(OpticalModel):
    def __init__(self, collector_cfg: dict, receiver_cfg: dict):
        self.aperture_m = collector_cfg["aperture_m"]
        self.focal_m = collector_cfg["focal_m"]
        self.sca_length_m = collector_cfg["sca_length_m"]
        self.d_abs_out_m = receiver_cfg["d_abs_out_m"]

    def build_deck(self) -> str:
        """生成 SolTrace .lk 脚本（几何定义），供 Windows 上 SolTrace 运行。"""
        return (
            "// SolTrace LK deck — parabolic trough (auto-generated by msptc)\n"
            f"// aperture width = {self.aperture_m} m, focal length = {self.focal_m} m\n"
            f"// SCA length = {self.sca_length_m} m, absorber OD = {self.d_abs_out_m} m\n"
            "addelement();\n"
            f"// surface: parabola z = x^2 / (4*{self.focal_m})\n"
            "// TODO: 填充 sunshape / optics / stage 定义并运行 st_sim()\n"
        )

    def parse_results(self, path: str):
        raise NotImplementedError("SolTrace 结果解析待接入实际 SolTrace 输出。")

    def efficiency(self, theta_deg: float) -> float:
        raise NotImplementedError(
            "SolTrace 引擎尚未接入；当前请使用 AnalyticalOptics。"
            "接入步骤：编译 NLR-SolTrace coretrace → pysoltrace 驱动 build_deck()。")

    def flux_on_absorber(self, theta_deg: float, dni: float) -> FluxProfile:
        raise NotImplementedError("SolTrace 通量分布待接入。")
