"""论文图表: 物理 + 经济 + 㶲分析 + 防冻 + 年度对比。投稿字体, Agg 后端, 双格式(PNG+PDF)输出。

投稿包清单:
  Paper A: Figure_01–Figure_06, Table_01–Table_08 → results/paper_a
           Figure_09 is generated by scripts.run_lcoe_honest
  Paper B: Figure_00, Figure_01–Figure_03, Figure_05, Table_01 → results/paper_b
"""
import argparse
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from msptc.io import load_config
from msptc.htf import make_htf
from msptc.receiver import ReceiverGeom
from msptc.atmosphere import AirProperties
from msptc.freeze import freeze_parasitic_W
from msptc.exergy import exergy_breakdown
from msptc.system import design_point
from scripts.run_altitude_sweep import run_altitude_sweep
from scripts.run_storage_htf_value import run_storage_htf_value
from scripts.run_aperture_sweep import run_aperture_sweep
from scripts.run_heatloss_split import run_heatloss_split

_LABELS = [("solar_salt", "Solar Salt", "o", "C0"), ("therminol_vp1", "Therminol VP-1", "s", "C1")]
_HTF_DESIGNS = [("solar_salt", 540.0), ("therminol_vp1", 390.0)]


def _setup_submission_font():
    """Artwork typography: Times New Roman, embedded in vector output."""
    from matplotlib import rcParams
    rcParams["font.family"] = ["Times New Roman"]
    rcParams["axes.unicode_minus"] = False
    rcParams["mathtext.fontset"] = "stix"
    rcParams["pdf.fonttype"] = 42
    rcParams["ps.fonttype"] = 42


def _save(fig, fname, outdir, pdf=True):
    base = os.path.join(outdir, fname.replace(".png", ""))
    png = base + ".png"
    fig.tight_layout()
    fig.savefig(png, dpi=150)
    if pdf:
        fig.savefig(base + ".pdf")
    plt.close(fig)
    return png


def _line_fig(df, xcol, ycol, yscale, xlabel, ylabel, title, fname, outdir, pdf=True):
    _setup_submission_font()
    fig, ax = plt.subplots(figsize=(6, 4))
    for htf, label, mk, color in _LABELS:
        d = df[df["htf_type"] == htf].sort_values(xcol)
        ax.plot(d[xcol], d[ycol] * yscale, marker=mk, color=color, label=label)
    ax.set_xlabel(xlabel); ax.set_ylabel(ylabel); ax.set_title(title)
    ax.legend(); ax.grid(True, alpha=0.3)
    return _save(fig, fname, outdir, pdf)


def _line_fig_with_diff(df, xcol, ycol, yscale, xlabel, ylabel, diff_label,
                        title, fname, outdir, pdf=True):
    """主 y 轴双线 + 次 y 轴熔盐−导热油差值柱。"""
    _setup_submission_font()
    fig, ax1 = plt.subplots(figsize=(7, 4))
    ax2 = ax1.twinx()
    pivot = {}
    for htf, label, mk, color in _LABELS:
        d = df[df["htf_type"] == htf].sort_values(xcol)
        xs, ys = d[xcol].values, d[ycol].values * yscale
        ax1.plot(xs, ys, marker=mk, color=color, label=label)
        pivot[htf] = (xs, ys)
    xs_s, ys_s = pivot.get("solar_salt", (np.array([]), np.array([])))
    xs_o, ys_o = pivot.get("therminol_vp1", (np.array([]), np.array([])))
    if len(xs_s) and len(xs_o):
        diff = ys_s - ys_o
        ax2.bar(xs_s, diff, alpha=0.25, color="gray", width=0.4, label=diff_label)
        ax2.axhline(0, color="gray", lw=0.6, ls="--")
    ax1.set_xlabel(xlabel); ax1.set_ylabel(ylabel); ax2.set_ylabel(diff_label)
    ax1.set_title(title)
    h1, l1 = ax1.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax1.legend(h1 + h2, l1 + l2, fontsize=8)
    ax1.grid(True, alpha=0.3)
    return _save(fig, fname, outdir, pdf)


def _fig_F2_exergy_waterfall(config_path, outdir, pdf=True):
    """Paper A Figure 2: 逐组件㶲损瀑布图 (设计点 DNI=900, T_amb=25°C)。"""
    _setup_submission_font()
    cfg = load_config(config_path)
    T_cold = cfg["htf"]["T_cold_C"]
    T_0_C = 25.0
    comp_labels = ["Optical +\nSolar Field", "Thermal\nStorage", "Power Block\nHeat→Elec.", "Net Electric\nOutput"]
    colors = ["#D46060", "#E09050", "#6080C0", "#50A060"]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5), sharey=True)
    for ax, (htf_type, T_hot_C) in zip(axes, _HTF_DESIGNS):
        dp = design_point(cfg, htf_type, T_hot_C=T_hot_C)
        Q_solar_W = dp["Q_useful_W"] / dp["eta_field"]
        T_field_m_C = 0.5 * (T_cold + dp["T_to_PB_C"])
        bd = exergy_breakdown(Q_solar_W, dp["Q_useful_W"], T_field_m_C,
                              dp["T_to_PB_C"], dp["P_elec_W"], T_0_C)
        Ex = bd["Ex_solar_W"]
        fracs = [
            bd["dest_optical_field_W"] / Ex * 100,
            bd["dest_storage_W"] / Ex * 100,
            bd["dest_powerblock_W"] / Ex * 100,
            dp["P_elec_W"] / Ex * 100,
        ]
        bars = ax.bar(comp_labels, fracs, color=colors, edgecolor="white", linewidth=0.5)
        for bar, frac in zip(bars, fracs):
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.5,
                    f"{frac:.1f}%", ha="center", va="bottom", fontsize=9)
        htf_name = "Solar Salt" if htf_type == "solar_salt" else "Therminol VP-1"
        ax.set_title(f"{htf_name}  η_ex = {bd['eta_exergy']*100:.1f}%")
        ax.set_ylabel("Fraction of Solar Exergy (%)")
        ax.set_ylim(0, 75)
        ax.grid(True, alpha=0.3, axis="y")

    fig.suptitle("Exergy Destruction by Component (Golmud Design Point, DNI = 900 W/m², T_amb = 25 °C)", fontsize=10)
    return _save(fig, "Figure_02_exergy_waterfall.png", outdir, pdf)


def _fig_F1_efficiency_dual(df_alt, outdir, pdf=True):
    """Paper A Figure 1: efficiency level plus altitude-induced relative change."""
    _setup_submission_font()
    fig, (ax_abs, ax_rel) = plt.subplots(1, 2, figsize=(9.5, 3.8))

    for htf, label, mk, color in _LABELS:
        d = df_alt[df_alt["htf_type"] == htf].sort_values("elev_m")
        xs = d["elev_m"].values
        ys = d["eta_solar_to_elec"].values * 100.0   # %
        delta_pp = ys - ys[0]

        ax_abs.plot(xs, ys, marker=mk, color=color, label=label)
        ax_rel.plot(xs, delta_pp, marker=mk, color=color, label=label)

        golmud = d[d["elev_m"] == 2801]
        if len(golmud):
            y_golmud = golmud["eta_solar_to_elec"].values[0] * 100.0
            delta_golmud = y_golmud - ys[0]
            short = "Salt" if htf == "solar_salt" else "Oil"
            offset = (10, 10) if htf == "solar_salt" else (10, -18)
            ax_rel.annotate(f"{short} +{delta_golmud:.4f} pp",
                            (2801, delta_golmud),
                            textcoords="offset points",
                            xytext=offset,
                            fontsize=8,
                            color=color)

    for ax in (ax_abs, ax_rel):
        ax.axvline(2801, color="gray", ls="--", lw=0.8)
        ax.grid(True, alpha=0.3)
        ax.set_xlabel("Elevation (m)")

    ax_abs.set_title("Absolute Efficiency Level")
    ax_abs.set_ylabel("Solar-to-Electric Efficiency (%)")
    ax_abs.legend(fontsize=8, loc="lower right")

    ax_rel.axhline(0, color="gray", lw=0.7, ls=":")
    ax_rel.set_title("Altitude Effect vs. Sea Level")
    ax_rel.set_ylabel("Efficiency Change (percentage points)")
    ax_rel.ticklabel_format(axis="y", style="plain", useOffset=False)
    ax_rel.text(2801 + 70, ax_rel.get_ylim()[0] * 0.9, "Golmud\n2801 m",
                fontsize=8, color="gray", va="bottom")

    fig.suptitle("Design-Point Efficiency: Level and Altitude-Induced Change",
                 fontsize=10)
    return _save(fig, "Figure_01_efficiency_vs_altitude.png", outdir, pdf)


def _fig_F3_freeze_vs_altitude(config_path, outdir, T_amb_C=-10.0, wind=3.0, pdf=True):
    """Paper A Figure 3: 防冻寄生功率 vs 海拔 + 熔盐/导热油比值。

    两种介质的防冻功率相差约 20 倍; 用同一 log y 轴和比值面板直接呈现
    量级差异,避免双 y 轴把大小关系视觉上压平。
    """
    _setup_submission_font()
    cfg = load_config(config_path)
    r = cfg["receiver"]
    geom = ReceiverGeom(
        d_abs_in_m=r["d_abs_in_m"], d_abs_out_m=r["d_abs_out_m"],
        d_glass_in_m=r["d_glass_in_m"], d_glass_out_m=r["d_glass_out_m"],
        eps_abs=r["eps_abs"], eps_glass=r["eps_glass"], vacuum=r["vacuum"],
    )
    L_total = cfg["collector"]["sca_length_m"] * cfg["collector"]["n_sca"]
    altitudes = [0, 500, 1000, 1500, 2000, 2500, 2801, 3000, 3500, 4000]

    data = {}
    for htf_type, _label, _mk, _color in _LABELS:
        htf = make_htf(htf_type)
        pws = []
        for elev in altitudes:
            air = AirProperties(elev)
            pw = freeze_parasitic_W(htf, geom, T_amb_C, wind, L_total,
                                    idle=True, air=air, sky_model="swinbank")
            pws.append(pw / 1000.0)
        data[htf_type] = np.array(pws)

    ratio = data["solar_salt"] / data["therminol_vp1"]
    fig, (ax_power, ax_ratio) = plt.subplots(1, 2, figsize=(8.2, 3.8))

    ax_power.plot(altitudes, data["solar_salt"], marker="o", color="C0",
                  label="Solar Salt")
    ax_power.plot(altitudes, data["therminol_vp1"], marker="s", color="C1",
                  label="Therminol VP-1")
    ax_power.set_yscale("log")
    ax_power.set_ylabel("Freeze-protection power (kW)")
    ax_power.legend(fontsize=8, loc="center right", framealpha=0.92)

    ax_ratio.plot(altitudes, ratio, marker="D", color="#7A3E9D")
    ax_ratio.axhline(20.0, color="0.5", lw=0.8, ls="--")
    ax_ratio.set_ylabel("Salt / Oil freeze-power ratio")
    ax_ratio.text(0.03, 0.90, "≈20x at -10 °C", transform=ax_ratio.transAxes,
                  fontsize=9, color="#5B2C6F", va="top")

    for ax, panel in [(ax_power, "(a)"), (ax_ratio, "(b)")]:
        ax.axvline(2801, color="gray", ls="--", lw=0.8)
        label_y = 0.14 if ax is ax_power else 0.72
        ax.text(2801 + 60, label_y, "Golmud\n2801 m",
                transform=ax.get_xaxis_transform(), fontsize=7,
                color="gray", va="bottom")
        ax.set_xlabel("Elevation (m)")
        ax.grid(True, alpha=0.25, which="both")
        ax.text(0.03, 0.94, panel, transform=ax.transAxes, fontsize=10,
                fontweight="bold", va="top")
    return _save(fig, "Figure_03_freeze_vs_altitude.png", outdir, pdf)


def _fig_F4_heatloss_dual_panel(df_alt, outdir, pdf=True):
    """Paper A Figure 4: heat-loss level plus altitude-induced relative change."""
    _setup_submission_font()
    fig, (ax_abs, ax_rel) = plt.subplots(1, 2, figsize=(9.5, 3.8))

    for htf, label, mk, color in _LABELS:
        d = df_alt[df_alt["htf_type"] == htf].sort_values("elev_m")
        xs = d["elev_m"].values
        q_kw = d["Q_loss_W"].values / 1000.0
        rel_pct = (q_kw / q_kw[0] - 1.0) * 100.0

        ax_abs.plot(xs, q_kw, marker=mk, color=color, label=label)
        ax_rel.plot(xs, rel_pct, marker=mk, color=color, label=label)

        golmud = d[d["elev_m"] == 2801]
        if len(golmud):
            q_golmud_kw = golmud["Q_loss_W"].values[0] / 1000.0
            rel_golmud = (q_golmud_kw / q_kw[0] - 1.0) * 100.0
            short = "Salt" if htf == "solar_salt" else "Oil"
            offset = (12, -22) if htf == "solar_salt" else (12, 10)
            ax_rel.annotate(f"{short} {rel_golmud:.2f}%",
                            (2801, rel_golmud),
                            textcoords="offset points",
                            xytext=offset,
                            fontsize=8,
                            color=color)

    for ax in (ax_abs, ax_rel):
        ax.axvline(2801, color="gray", ls="--", lw=0.8)
        ax.grid(True, alpha=0.3)
        ax.set_xlabel("Elevation (m)")
    ax_abs.set_title("Absolute Heat-Loss Level")
    ax_abs.set_ylabel("Collector Field Heat Loss (kW)")
    ax_abs.legend(fontsize=8)

    ax_rel.axhline(0, color="gray", lw=0.7, ls=":")
    ax_rel.set_title("Altitude Effect vs. Sea Level")
    ax_rel.set_ylabel("Heat-Loss Change (%)")
    ax_rel.set_yticks(np.linspace(-0.4, 0.0, 5))
    ax_rel.yaxis.set_major_formatter(lambda x, _pos: f"{x:.1f}%")
    ax_rel.text(2801 + 70, -0.36, "Golmud\n2801 m",
                fontsize=8, color="gray", va="bottom")

    fig.suptitle("Collector Field Heat Loss: Level and Altitude-Induced Change",
                 fontsize=10)
    return _save(fig, "Figure_04_heatloss_vs_altitude.png", outdir, pdf)


def _fig_F5_annual_comparison(outdir, pdf=True):
    """Paper A Figure 5: 年度净发电量对比 (晴空/TMY × 海平面/高原 × 两介质)。"""
    _setup_submission_font()
    cases = [
        ("Clear-sky\nSea Level",
         _first_existing(outdir, "Table_04_system_annual_clearsky_sea_level.csv",
                         "system_annual_clearsky_sea_2023.csv")),
        ("Clear-sky\nAltitude",
         _first_existing(outdir, "Table_05_system_annual_clearsky_golmud.csv",
                         "system_annual_clearsky_alt_2023.csv")),
        ("TMY\nSea Level",
         _first_existing(outdir, "Table_06_system_annual_tmy_sea_level.csv",
                         "system_annual_tmy_sea_2023.csv")),
        ("TMY\nAltitude",
         _first_existing(outdir, "Table_07_system_annual_tmy_golmud.csv",
                         "system_annual_tmy_alt_2023.csv")),
    ]
    missing = [p for _, p in cases if not os.path.exists(p)]
    if missing:
        raise RuntimeError(_missing_annual_tables_message(outdir, missing))

    x = np.arange(len(cases))
    width = 0.35
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for i, (htf_type, label, _, color) in enumerate(_LABELS):
        vals = []
        for _, path in cases:
            df = pd.read_csv(path)
            df.columns = df.columns.str.strip("﻿")
            row = df[df["htf_type"] == htf_type]
            vals.append(row["P_elec_MWh"].values[0] if len(row) else 0.0)
        bars = ax.bar(x + (i - 0.5) * width, vals, width, color=color,
                      label=label, edgecolor="white")
        for bar, v in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 8,
                    f"{v:.0f}", ha="center", va="bottom", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels([c for c, _ in cases])
    ax.set_ylabel("Annual Net Electricity Generation (MWh)")
    ax.set_title("Annual Net Electricity: Clear-sky / TMY  ×  Sea Level / Altitude (Golmud)")
    ax.legend(); ax.grid(True, alpha=0.3, axis="y")
    return _save(fig, "Figure_05_annual_comparison.png", outdir, pdf)


def _fig_F8_value_heatmap(df_val, outdir, pdf=True):
    """Paper A Figure 8: 储热价值面热力图 — LCOE 与价值因子 (2 介质 × 储热小时数)。"""
    _setup_submission_font()
    htfs = ["solar_salt", "therminol_vp1"]
    htf_labels = ["Solar Salt", "Therminol VP-1"]
    hours = sorted(df_val["storage_hours"].unique())

    def _matrix(col):
        M = np.zeros((len(htfs), len(hours)))
        for i, h in enumerate(htfs):
            for j, s in enumerate(hours):
                v = df_val[(df_val["htf_type"] == h) & (df_val["storage_hours"] == s)][col]
                if len(v):
                    M[i, j] = v.values[0]
        return M

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3))
    for ax, col, cmap, title, fmt in [
        (ax1, "LCOE_CNY_MWh", "RdYlGn_r", "LCOE (CNY/MWh)", "{:.0f}"),
        (ax2, "value_factor",  "RdYlGn",   "Value Factor",    "{:.3f}"),
    ]:
        M = _matrix(col)
        im = ax.imshow(M, cmap=cmap, aspect="auto")
        fig.colorbar(im, ax=ax, shrink=0.9)
        ax.set_xticks(range(len(hours))); ax.set_xticklabels([f"{h}h" for h in hours])
        ax.set_yticks(range(len(htf_labels))); ax.set_yticklabels(htf_labels)
        ax.set_xlabel("Storage Hours (h)"); ax.set_title(title)
        for i in range(len(htfs)):
            for j in range(len(hours)):
                ax.text(j, i, fmt.format(M[i, j]), ha="center", va="center",
                        fontsize=9, color="black")
    fig.suptitle("Storage × HTF Value Surface (LCOE and Value Factor)", fontsize=10)
    return _save(fig, "Figure_08_value_heatmap.png", outdir, pdf)


def _first_existing(outdir, preferred, legacy):
    preferred_path = os.path.join(outdir, preferred)
    if os.path.exists(preferred_path):
        return preferred_path
    return os.path.join(outdir, legacy)


def _fig_F6_lcoe_vs_storage(df_val, outdir, pdf=True):
    """Paper A Figure 6: idealized clear-sky LCOE mechanism, freeze excluded.

    Top panel shows the two LCOE curves; bottom panel shows the salt-oil cost
    difference on its own axis, avoiding a dual-y plot.
    """
    _setup_submission_font()
    fig, (ax_lcoe, ax_delta) = plt.subplots(
        2, 1, figsize=(7.0, 5.0), sharex=True,
        gridspec_kw={"height_ratios": [3.0, 1.15], "hspace": 0.08},
    )
    curves = {}
    for htf, label, mk, color in _LABELS:
        d = df_val[df_val["htf_type"] == htf].sort_values("storage_hours")
        xs = d["storage_hours"].values
        ys = d["LCOE_CNY_MWh"].values
        curves[htf] = (xs, ys)
        ax_lcoe.plot(xs, ys, marker=mk, color=color, lw=1.8, label=label)
        i_min = int(np.argmin(ys))
        ax_lcoe.annotate(f"min {ys[i_min]:.0f}",
                         (xs[i_min], ys[i_min]),
                         textcoords="offset points",
                         xytext=(0, -18 if htf == "solar_salt" else 10),
                         ha="center", fontsize=8, color=color)

    xs = curves["solar_salt"][0]
    delta = curves["solar_salt"][1] - curves["therminol_vp1"][1]
    bar_colors = ["#4C78A8" if v <= 0 else "#C44E52" for v in delta]
    ax_delta.bar(xs, delta, width=0.55, color=bar_colors, alpha=0.68)
    ax_delta.axhline(0, color="0.35", lw=0.8)

    ax_lcoe.set_ylabel("LCOE (CNY/MWh)")
    ax_delta.set_ylabel("Salt - Oil\n(CNY/MWh)")
    ax_delta.set_xlabel("Thermal-storage hours (h)")
    ax_delta.set_xticks(xs)
    ax_lcoe.legend(fontsize=8, loc="upper left", framealpha=0.92)
    ax_lcoe.text(0.98, 0.94, "Idealized clear-sky; freeze excluded",
                 transform=ax_lcoe.transAxes, ha="right", va="top",
                 fontsize=8, color="0.35")
    for ax in (ax_lcoe, ax_delta):
        ax.grid(True, alpha=0.25, axis="y")
    return _save(fig, "Figure_06_lcoe_vs_storage.png", outdir, pdf)


def _missing_annual_tables_message(outdir, missing):
    missing_lines = "\n".join(f"  - {p}" for p in missing)
    return (
        "Cannot build Paper A Figure_05_annual_comparison.png because annual "
        f"input tables are missing:\n{missing_lines}\n\n"
        "Generate or rename the four annual manuscript tables, for example:\n"
        f"  python -m scripts.run_system_annual --weather clearsky --outdir {outdir}\n"
        f"  python -m scripts.run_system_annual --weather clearsky --altitude --outdir {outdir}\n"
        f"  python -m scripts.run_system_annual --weather tmy --outdir {outdir}\n"
        f"  python -m scripts.run_system_annual --weather tmy --altitude --outdir {outdir}\n\n"
        "Expected manuscript table names are:\n"
        "  - Table_04_system_annual_clearsky_sea_level.csv\n"
        "  - Table_05_system_annual_clearsky_golmud.csv\n"
        "  - Table_06_system_annual_tmy_sea_level.csv\n"
        "  - Table_07_system_annual_tmy_golmud.csv"
    )


def run_paper_figures(config_path="config/default.json", outdir="results", pdf=True):
    os.makedirs(outdir, exist_ok=True)
    df_alt = run_altitude_sweep(config_path, outdir=outdir,
                                csv_name="Table_01_altitude_sweep.csv")
    df_val = run_storage_htf_value(config_path, outdir=outdir,
                                   storage_hours=[0, 3, 6, 9, 12],
                                   csv_name="Table_02_storage_htf_value.csv")
    run_heatloss_split(config_path, outdir=outdir,
                       csv_name="Table_08_heatloss_split.csv")
    paths = [
        _fig_F1_efficiency_dual(df_alt, outdir, pdf),
        _fig_F2_exergy_waterfall(config_path, outdir, pdf),
        _fig_F3_freeze_vs_altitude(config_path, outdir, pdf=pdf),
        _fig_F4_heatloss_dual_panel(df_alt, outdir, pdf),
        _fig_F6_lcoe_vs_storage(df_val, outdir, pdf),
    ]
    f5 = _fig_F5_annual_comparison(outdir, pdf)
    paths.append(f5)
    paths = [p for p in paths if p]
    print("图表输出:", paths)
    return paths


def _fig_F9_gamma_vs_aperture(config_path, outdir, pdf=True):
    """Paper B Figure 1: 纯几何截距因子 γ vs 开口宽度（按吸热管直径分族）。

    本图属 §2(误差锥)，在 §4 风载耦合之前，故只画**静态光学预算**(不含风载项)的
    内禀光学标度,与 §2 正文数值一致。风载-海拔效应见协同主图 Fig 5。
    """
    from msptc.optics.intercept import intercept_factor, sigma_total
    _setup_submission_font()
    eb = load_config(config_path)["optics"]["error_budget"]
    st = sigma_total(eb["sigma_sun_mrad"] * 1e-3, eb["sigma_slope_grav_mrad"] * 1e-3,
                     eb["sigma_spec_mrad"] * 1e-3, eb["sigma_track_mrad"] * 1e-3)
    focals = {5.77: 1.71, 6.0: 1.78, 7.5: 2.23, 8.6: 2.56}
    Ws = [5.77, 6.0, 7.5, 8.6]
    fig, ax = plt.subplots(figsize=(6.8, 4.25))
    for D, mk, color in [(0.070, "o", "#4C78A8"), (0.080, "^", "#F28E2B"),
                         (0.090, "s", "#59A14F")]:
        g = [intercept_factor(W, focals[W], D, st) for W in Ws]
        ax.plot(Ws, g, marker=mk, color=color, lw=1.7,
                label=f"Absorber OD {int(D*1000)} mm")
    for W, label in [(5.77, "EuroTrough"), (7.5, "Ultimate"), (8.6, "8.6 m class")]:
        ax.axvline(W, color="0.75", lw=0.7, ls=":")
        ax.text(W, 0.04, label, transform=ax.get_xaxis_transform(),
                ha="center", va="bottom", fontsize=7, color="0.35")
    ax.axhline(0.98, color="0.55", lw=0.8, ls="--")
    ax.text(8.58, 0.9815, "0.98 reference", ha="right", va="bottom",
            fontsize=7, color="0.35")
    ax.set_xlabel("Aperture width (m)")
    ax.set_ylabel("Intercept factor γ")
    ax.set_xlim(5.55, 8.75)
    ax.set_ylim(0.915, 1.004)
    ax.legend(fontsize=8, loc="upper center", bbox_to_anchor=(0.5, -0.16),
              ncol=3, framealpha=0.92)
    ax.grid(True, alpha=0.25, axis="y")
    return _save(fig, "Figure_01_gamma_vs_aperture.png", outdir, pdf)


def _fig_F10_concentration_heatloss(df_ap, outdir, pdf=True, config_path="config/default.json"):
    """Paper B Figure 3: 聚光比 C 与**相对**热损 vs 开口（Solar Salt, 海平面, 70mm）。

    相对热损 = 场热损 / 入射光功率(DNI·采光面积)。绝对热损按吸热管长度近恒定,
    但采光面积随开口增大,故相对热损随开口下降——这才是"大开口降相对热损"的可见证据。
    """
    _setup_submission_font()
    cfg = load_config(config_path)
    L_total = cfg["collector"]["sca_length_m"] * cfg["collector"]["n_sca"]
    dni = 900.0
    d = df_ap[(df_ap["htf_type"] == "solar_salt") & (df_ap["elev_m"] == 0)
              & (df_ap["d_abs_out_m"] == 0.070)].sort_values("aperture_m")
    rel_loss = d["Q_loss_W"] / (dni * d["aperture_m"] * L_total) * 100.0
    fig, (ax_c, ax_l) = plt.subplots(1, 2, figsize=(7.3, 3.6), sharex=True)
    ax_c.plot(d["aperture_m"], d["concentration"], marker="o", color="#4C78A8", lw=1.8)
    ax_l.plot(d["aperture_m"], rel_loss, marker="s", color="#C44E52", lw=1.8)
    ax_c.margins(y=0.14)
    ax_l.margins(y=0.14)

    ax_c.set_ylabel("Geometric concentration C")
    ax_l.set_ylabel("Relative heat loss (% of incident)")
    for ax, panel in [(ax_c, "(a)"), (ax_l, "(b)")]:
        ax.set_xlabel("Aperture width (m)")
        ax.grid(True, alpha=0.25)
        ax.text(0.03, 0.94, panel, transform=ax.transAxes, fontsize=10,
                fontweight="bold", va="top")
    ax_c.annotate(f"{d['concentration'].iloc[-1]:.1f}",
                  (d["aperture_m"].iloc[-1], d["concentration"].iloc[-1]),
                  textcoords="offset points", xytext=(-5, -16), ha="right", fontsize=8)
    ax_l.annotate(f"{rel_loss.iloc[-1]:.2f}%",
                  (d["aperture_m"].iloc[-1], rel_loss.iloc[-1]),
                  textcoords="offset points", xytext=(-5, 8), ha="right", fontsize=8)
    return _save(fig, "Figure_02_concentration_heatloss.png", outdir, pdf)


def _fig_F11_altitude_synergy(df_ap, outdir, pdf=True, config_path="config/default.json"):
    """Paper B Figure 3 (协同主图, 纯光学通道): 海拔-风载协同——截距因子从海平面到格尔木的增益 Δγ
    随开口增大而单调增大,即"大开口在高原不成比例受益"。

    固定吸热管 70mm + 熔盐, 仅开口变化, 隔离纯几何/光学效应;
    热-海拔通道(对流热损/效率)由 companion paper A 的 F1/F4 承担, 此处不混入。
    """
    _setup_submission_font()
    from msptc.atmosphere import AirProperties
    from msptc.optics.intercept import intercept_factor, sigma_total
    from msptc.optics.wind_deflection import sigma_slope_wind

    apertures = [5.77, 7.5, 8.6]
    focals = {5.77: 1.71, 7.5: 2.23, 8.6: 2.56}
    d = df_ap[(df_ap["htf_type"] == "solar_salt") & (df_ap["d_abs_out_m"] == 0.070)]

    def _g(W, elev):
        s = d[(d["aperture_m"] == W) & (d["elev_m"] == elev)]["gamma"]
        return s.values[0] if len(s) else float("nan")

    central = np.array([(_g(W, 2801) - _g(W, 0)) * 1e3 for W in apertures])

    cfg = load_config(config_path)
    eb = cfg["optics"]["error_budget"]
    wind_cfg = cfg["wind"]
    sun = eb["sigma_sun_mrad"] * 1e-3
    slope_grav = eb["sigma_slope_grav_mrad"] * 1e-3
    spec = eb["sigma_spec_mrad"] * 1e-3
    track = eb["sigma_track_mrad"] * 1e-3
    v_design = wind_cfg["v_design_ms"]
    t_design = wind_cfg.get("t_amb_design_C", 20.0)
    w_ref = wind_cfg["w_ref_m"]

    def _wind_loaded_gamma(W, elev, c_w, aperture_exp):
        rho = AirProperties(elev).rho(t_design)
        slope_wind = sigma_slope_wind(rho, v_design, W, c_w, aperture_exp, w_ref)
        slope = np.sqrt(slope_grav ** 2 + slope_wind ** 2)
        st = sigma_total(sun, slope, spec, track)
        return intercept_factor(W, focals[W], 0.070, st)

    band = []
    for W in apertures:
        vals = []
        for c_w in (1.0e-5, 1.7e-5, 2.5e-5):
            for aperture_exp in (1.0, 1.5, 2.0):
                vals.append((_wind_loaded_gamma(W, 2801, c_w, aperture_exp)
                             - _wind_loaded_gamma(W, 0, c_w, aperture_exp)) * 1e3)
        band.append(vals)
    band = np.array(band)
    lower = band.min(axis=1)
    upper = band.max(axis=1)

    fig, ax = plt.subplots(figsize=(6.8, 4.1))
    ax.fill_between(apertures, lower, upper, color="#C44E52", alpha=0.18,
                    linewidth=0, label="Sensitivity band (9 wind-load cases)")
    ax.plot(apertures, central, marker="D", color="#C44E52", lw=2.0,
            label="Central coefficients")
    for W, dg in zip(apertures, central):
        ax.annotate(f"+{dg:.1f}", (W, dg), textcoords="offset points",
                    xytext=(0, 8), ha="center", fontsize=8, color="#8B1A1A")
    ax.set_xticks(apertures)
    ax.set_xticklabels(["5.77\nEuroTrough", "7.50\nUltimate", "8.60\nlarge aperture"])
    ax.set_xlabel("Aperture width (m)")
    ax.set_ylabel("Altitude gain Δγ (x 10^-3)")
    ax.set_xlim(5.55, 8.82)
    ax.set_ylim(0, max(upper) * 1.12)
    ax.grid(True, alpha=0.28, axis="y")
    ax.legend(fontsize=8, loc="upper left", framealpha=0.92)
    ax.text(0.98, 0.05, "70 mm absorber; wind-loaded intercept difference",
            transform=ax.transAxes, ha="right", va="bottom", fontsize=8, color="0.35")
    return _save(fig, "Figure_03_altitude_synergy.png", outdir, pdf)


def _fig_F12_efficiency_vs_aperture(df_ap, outdir, pdf=True):
    """Paper B Figure 4: 太阳能到电效率 vs 开口（格尔木, 吸热管 90mm）。"""
    _setup_submission_font()
    fig, ax = plt.subplots(figsize=(6, 4))
    for htf, label, mk, color in _LABELS:
        d = df_ap[(df_ap["htf_type"] == htf) & (df_ap["elev_m"] == 2801)
                  & (df_ap["d_abs_out_m"] == 0.090)].sort_values("aperture_m")
        ax.plot(d["aperture_m"], d["eta_solar_to_elec"] * 100, marker=mk, color=color, label=label)
    ax.set_xlabel("Aperture Width (m)"); ax.set_ylabel("Solar-to-Electric Efficiency (%)")
    ax.set_title("Efficiency vs. Aperture at Altitude (Golmud, Absorber OD 90 mm)")
    ax.legend(); ax.grid(True, alpha=0.3)
    return _save(fig, "Figure_04_efficiency_vs_aperture.png", outdir, pdf)


def _fig_F13_intercept_validation(config_path, outdir, pdf=True):
    """Paper B Figure 5 (验证 parity): 误差锥模型 γ vs 第三方实测 8.6m SCE 拦截率。

    锚点: 中广核 8.6m/80mm = 0.966(德令哈中试); 龙腾 RT86 8.6m/90mm ≥ 0.98(临河示范)。
    模型在默认误差预算(σ_slope_grav=2.5mrad)下复现实测值, 误差 <~1%。
    """
    from msptc.optics.intercept import intercept_factor, sigma_total
    _setup_submission_font()
    eb = load_config(config_path)["optics"]["error_budget"]
    st = sigma_total(eb["sigma_sun_mrad"] * 1e-3, eb["sigma_slope_grav_mrad"] * 1e-3,
                     eb["sigma_spec_mrad"] * 1e-3, eb["sigma_track_mrad"] * 1e-3)
    cgn_model = intercept_factor(8.6, 2.56, 0.080, st)
    lt_model = intercept_factor(8.6, 2.56, 0.090, st)
    euro_model = intercept_factor(5.77, 1.71, 0.070, st)

    fig, ax = plt.subplots(figsize=(5.4, 4.4))
    lims = (0.955, 0.995)
    ax.plot(lims, lims, color="0.45", lw=0.9, ls="--", label="1:1 line")
    ax.scatter([0.966], [cgn_model], s=58, marker="o", color="#4C78A8",
               label="Reported value")
    ax.annotate(f"CGN 80 mm\nmodel {cgn_model:.3f}",
                (0.966, cgn_model), textcoords="offset points",
                xytext=(-38, 16), fontsize=8, color="#2F5F8F")

    ax.scatter([0.980], [lt_model], s=66, marker="^", facecolors="white",
               edgecolors="#C44E52", linewidths=1.4, label="Reported lower bound")
    ax.annotate("", xy=(0.993, lt_model), xytext=(0.980, lt_model),
                arrowprops=dict(arrowstyle="->", color="#C44E52", lw=1.2))
    ax.annotate(f"Longteng 90 mm\nmeasured ≥0.980\nmodel {lt_model:.3f}",
                (0.980, lt_model), textcoords="offset points",
                xytext=(-12, -42), fontsize=8, color="#8B1A1A")

    ax.text(0.03, 0.06,
            f"EuroTrough 5.77/70 model reference γ={euro_model:.3f}\n"
            "no directly comparable intercept measurement",
            transform=ax.transAxes, fontsize=8, color="0.35",
            bbox=dict(boxstyle="round,pad=0.24", fc="white", ec="0.82", alpha=0.95))
    ax.set_xlim(lims)
    ax.set_ylim(lims)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("Measured intercept factor γ")
    ax.set_ylabel("Model intercept factor γ")
    ax.legend(fontsize=8, loc="upper left", framealpha=0.92)
    ax.grid(True, alpha=0.25)
    return _save(fig, "Figure_05_intercept_validation.png", outdir, pdf)


def _fig_geometry_schematic(outdir, pdf=True):
    """Paper B Figure 1 (schematic, not to scale): parabolic-trough optics —
    aperture W, focal length f, rim angle φ_r, absorber tube, and the local
    acceptance half-angle Δθ versus the optical error cone that defines γ.

    Pure illustration (no simulation data); proportions chosen for a rim angle
    of ~80° and an exaggerated absorber radius for legibility.
    """
    import math as _m
    from matplotlib.patches import Arc, Polygon, Circle
    _setup_submission_font()

    f = 1.0
    W = 3.357                       # -> rim angle ~80°
    half = W / 2.0
    xs = np.linspace(-half, half, 400)
    ys = xs ** 2 / (4.0 * f)
    F = np.array([0.0, f])
    y_rim = half ** 2 / (4.0 * f)

    fig, ax = plt.subplots(figsize=(6.8, 3.8))
    ax.plot(xs, ys, color="#22507A", lw=2.6, zorder=3)          # mirror
    ax.plot([0, 0], [0, f], color="gray", ls=":", lw=1.0)       # optical axis

    R = 0.14                                                     # exaggerated absorber radius
    ax.add_patch(Circle(F, R, fill=False, ec="#C0392B", lw=2.0, zorder=6))
    ax.plot(*F, marker="+", color="#C0392B", ms=9, mew=1.8, zorder=7)

    # aperture width arrow (above the absorber to avoid clutter)
    ya = f + 0.34
    ax.annotate("", xy=(half, ya), xytext=(-half, ya),
                arrowprops=dict(arrowstyle="<->", color="black", lw=1.2))
    ax.text(0, ya + 0.05, "Aperture W", ha="center", va="bottom", fontsize=11)
    ax.plot([-half, -half], [y_rim, ya], color="gray", lw=0.6, ls="--")
    ax.plot([half, half], [y_rim, ya], color="gray", lw=0.6, ls="--")

    # focal length arrow
    ax.annotate("", xy=(0, f), xytext=(0, 0),
                arrowprops=dict(arrowstyle="<->", color="dimgray", lw=1.1))
    ax.text(0.05, f / 2, "f", ha="left", va="center", fontsize=11, color="dimgray")

    # rim angle
    Prim = np.array([half, y_rim])
    ax.plot([F[0], Prim[0]], [F[1], Prim[1]], color="#7F8C8D", lw=1.0)
    ang_axis = _m.degrees(_m.atan2(0 - f, 0.0))                 # -90 (downward)
    ang_rim = _m.degrees(_m.atan2(Prim[1] - f, Prim[0]))
    ax.add_patch(Arc(F, 0.9, 0.9, angle=0,
                     theta1=min(ang_axis, ang_rim), theta2=max(ang_axis, ang_rim),
                     color="#7F8C8D", lw=1.2))
    ax.text(0.27, f - 0.46, "φr", fontsize=13, color="#566573")

    # mirror element: incident ray, reflected ray, acceptance cone, error cone
    Px = 1.30
    P = np.array([Px, Px ** 2 / (4.0 * f)])
    ax.annotate("", xy=(P[0], P[1]), xytext=(P[0], y_rim + 0.38),
                arrowprops=dict(arrowstyle="->", color="#E67E22", lw=1.6))
    ax.text(P[0] + 0.04, y_rim + 0.34, "incident\nrays", fontsize=8,
            color="#E67E22", va="top")

    d = F - P
    dist = float(np.linalg.norm(d))
    u = d / dist
    perp = np.array([-u[1], u[0]])
    e1, e2 = F + R * perp, F - R * perp
    ax.add_patch(Polygon([P, e1, e2], closed=True, facecolor="#BDC3C7",
                         alpha=0.45, edgecolor="none", zorder=2))         # acceptance
    ax.plot([P[0], F[0]], [P[1], F[1]], color="#C0392B", lw=1.3, zorder=4)

    sig = _m.radians(4.2)
    base = _m.atan2(u[1], u[0])
    a1, a2 = base + sig, base - sig
    ax.add_patch(Polygon([P, P + dist * np.array([_m.cos(a1), _m.sin(a1)]),
                          P + dist * np.array([_m.cos(a2), _m.sin(a2)])],
                         closed=True, facecolor="#E67E22", alpha=0.32,
                         edgecolor="none", zorder=2))                     # error cone
    ax.text(P[0] - 0.42, P[1] + 0.20, "acceptance Δθ", fontsize=10, color="#34495E")
    ax.text(0.68, 0.52, "error cone σtot", fontsize=10, color="#B9651B")

    ax.text(F[0] - R - 0.07, F[1] + 0.11, "Absorber D", fontsize=10,
            color="#C0392B", ha="right", va="bottom")

    ax.set_aspect("equal")
    ax.set_xlim(-half - 0.18, half + 0.18)
    ax.set_ylim(-0.12, f + 0.55)
    ax.axis("off")
    return _save(fig, "Figure_00_geometry_schematic.png", outdir, pdf)


def run_aperture_figures(config_path="config/default.json", outdir="results",
                         pdf=True, c_w=1.7e-5):
    """Paper B 开口维度投稿图 Figure_00、Figure_01–Figure_03、Figure_05。"""
    os.makedirs(outdir, exist_ok=True)
    df_ap = run_aperture_sweep(config_path, outdir=outdir, elevations=[0, 2801],
                               c_w=c_w, csv_name="Table_01_aperture_sweep.csv")
    paths = [
        _fig_geometry_schematic(outdir, pdf),
        _fig_F9_gamma_vs_aperture(config_path, outdir, pdf),
        _fig_F10_concentration_heatloss(df_ap, outdir, pdf),
        _fig_F11_altitude_synergy(df_ap, outdir, pdf),
        # _fig_F12_efficiency_vs_aperture: 已从 Paper B 手稿删除(§5 太阳能→电效率
        # 章整章移交 companion paper,见 figure-list.md)。函数保留但不再纳入投稿包。
        _fig_F13_intercept_validation(config_path, outdir, pdf),
    ]
    print("开口维度图表输出:", paths)
    return paths


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="生成两篇 SCI 投稿包图表 (A→paper_a, B→paper_b 分目录)")
    ap.add_argument("--config", default="config/default.json")
    ap.add_argument("--outdir", default="results")
    ap.add_argument("--no-pdf", action="store_false", dest="pdf")
    a = ap.parse_args()
    # Paper A (高原 4E): Figure_01–Figure_06 → results/paper_a
    # Figure_09 is generated by scripts.run_lcoe_honest.
    run_paper_figures(a.config, outdir=os.path.join(a.outdir, "paper_a"), pdf=a.pdf)
    # Paper B (大开口光学): Figure_00、Figure_01–Figure_03、Figure_05 → results/paper_b
    run_aperture_figures(a.config, outdir=os.path.join(a.outdir, "paper_b"), pdf=a.pdf)
